### ISSUE TITLE
[文案]邀请 Guido 分享祝贺视频

### ISSUE THREAD

**Issue by ZoomQuiet** [PyConChina/PyConCN#93]
## 背景
- PyConChina 第5年了
- Guido 依然来不了
- 但是,纪念 TEE 是必须上身的 ;-)
## 目标

邀请 Guido 录制一份儿两分钟的视频来祝贺 PyConChina 的成功,
以及鼓励中国 Pythonista 们.
### 正文:

Dear Guido:

very glad tell u , PyConChina 2015 will celebrate in Sep.
sadly we can not invite u come China for speech.
but very hope u make shot video for whole Chinese Pythonista
- about 2 minute
- publish youtube , reply email the URL
- just encourage Chinese coder enjoy new python etc.

the detail all in offical site:
    http://cn.pycon.org/2015/

calendar as:
- 2015-9-12 9:00- 18:00 (UTC+8) 400+ attendee at Shanghai 
- 2015-9-13 9:00- 18:00 (UTC+8) 200+ attendee at Guangzhou
- 2015-9-19 9:00- 18:00 (UTC+8) 400+ attendee at Beijing 
- 2013-9-20 9:00- 18:00 (UTC+8) 70+ attendee at Hangzhou

btw:
- thist year we upgrade commemoration T-shirt
- invitation one pretty calligrapher girl handwritten the slogen
- if u post addr. changed, pls. tell us, gift one for u ;-)

![pyconchina2015tee](https://cloud.githubusercontent.com/assets/22494/9605739/1a326402-50f2-11e5-8b31-58c3e62ae6c6.jpg)

**Comment by aJiea** [comment]
Subjet: Congratulation Video for PyConChina 2015 Celebration Ceremony 

Dear Guido,

I’m glad to tell you that PyConChina 2015 will be held this month.
Unfortunately this year we are not able to invite you to the ceremony for the speech in person.
But your words have great impact among Chinese Pythonista, so I was wondering if you would like to make a  short video for us: 

about 2 minute, to encourage Chinese coder enjoying new python, etc.
publish it on youtube , and send us the URL by email reply
As for the details c.f.
http://cn.pycon.org/2015/

Schedule:

2015-9-12 9:00- 18:00 (UTC+8) 400+ attendee at Shanghai 
2015-9-13 9:00- 18:00 (UTC+8) 200+ attendee at Guangzhou
2015-9-19 9:00- 18:00 (UTC+8) 400+ attendee at Beijing 
2013-9-20 9:00- 18:00 (UTC+8) 70+ attendee at Hangzhou
BTW pls tell me your postal address so that I could send you the T-shirt of this year (calligraphy by a pretty girl).

Thanks ahead!

 Best regards,

**Comment by ZoomQuiet** [comment]
```
from:   Guido van Rossum 
to: "Zoom.Quiet" 
cc: support@pychina.org
date:   Wed, Sep 9, 2015 at 12:41 AM
subject:    Re: Congratulation Video for PyConChina 2015 Celebration Ceremony ..[was] PyCon2014China T-shirt coming on
```

...PS: I don't know if gender discrimination is an issue in Chinese culture, but in the US and Europe, if you wrote "calligraphy by a pretty girl" you'd raise a few eyebrows -- what do I care about whether she is pretty (or about the gender of the calligrapher at all), as long as the calligraphy itself is pretty? (Which I'm sure it is!)

嗯哼!?

**Comment by wuyating** [comment]
I'm sorry that my inappropriate expression has led to your misunderstanding. When I said "calligraphy by a pretty girl", what I intended to stress was  "calligraphy" because the characters on the T-shirt this year was WRITTEN instead of printed, and the "pretty girl" is the writter of the characters. Thank you for your reminding and I'll pay attention to this problem in English expression. Btw, gender equity is now an important issue in China and it gains close attention of an increasing number of Chinese people.

**Comment by ZoomQuiet** [comment]
@aJiea For your question about gender discrimination, “pretty girl” in Mandarin is “Meinv. And Meinv lost is literary meaning and became a personal pronoun. Handsome man(Shuaige in Chinese) for male. In China you can feel free to use Meinv or Shuaige to start a conversation or to talk about someone without causing problems. 
When I said the calligraphy was written by a pretty girl I wanted to say that it was someone in our team who did it. Sometimes in a language, the gender of the person can be revealed, like in French, par une calligraphe(female), par un calligraphe(male). I guess that’s why there’s alternative to use, for example, police officer instead of police women in English to avoid gender discrimination issues.
In China gender discrimination does exist, but definitely not in this case, not in the invitation.

**Comment by ZoomQuiet** [comment]
DAMA-style:

> PS: I don't know if gender discrimination is an issue in Chinese culture, 
> but in the US and Europe, if you wrote "calligraphy by a pretty girl" you'd raise a few eyebrows 
> -- what do I care about whether she is pretty (or about the gender of the calligrapher at all), 
> - for Chinese default imagination, calligrapher always one old man
> - so one girl as calligrapher is very surprised
> - and is one pretty girl as calligrapher means big News ;-)
> 
> as long as the calligraphy itself is pretty? (Which I'm sure it is!)
> - as calligraphy is already means the works must be pretty
> - btw: wuyating (https://github.com/wuyating) is the "pretty girl calligrapher"
> - she is happy for my define as "pretty girl calligrapher" ;-)
